<?php
$pageTitle = 'Disclaimer – aNepaliSewa';
$pageDesc  = 'Read the disclaimer for aNepaliSewa. Our tools are for informational purposes only. Always verify critical information through official sources.';
include 'includes/header.php';
?>
<div class="page-hero"><div class="container"><h1 class="page-hero-title">Disclaimer</h1><p class="page-hero-subtitle">Last Updated: <?php echo date('F Y'); ?></p></div></div>
<section class="content-section"><div class="container"><div class="row justify-content-center"><div class="col-lg-9"><div class="card-content">
  <div class="alert alert-custom mb-4" style="background:rgba(245,158,11,.08);border:1px solid var(--warning);color:var(--text-main);">
    <i class="bi bi-exclamation-triangle text-warning me-2"></i>
    <strong>Important:</strong> The tools and information on aNepaliSewa are provided for general informational and educational purposes only.
  </div>
  <h4 class="fw-bold mt-4"><i class="bi bi-info-circle text-primary me-2"></i>General Disclaimer</h4>
  <p class="text-muted">The tools, calculators, and converters provided by <strong>aNepaliSewa</strong> are intended for general use only. While we strive to provide accurate and up-to-date information and results, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the tools or the information generated by them.</p>
  <h4 class="fw-bold mt-4"><i class="bi bi-calendar3 text-primary me-2"></i>Date Converter Disclaimer</h4>
  <p class="text-muted">The Nepali (Bikram Sambat) date conversion is based on algorithmically computed calendar data. While we aim for accuracy, the conversion results should be verified against official Nepali government calendars, especially for official, legal, or financial purposes. Small discrepancies may exist in edge cases.</p>
  <h4 class="fw-bold mt-4"><i class="bi bi-calculator text-primary me-2"></i>GPA Calculator Disclaimer</h4>
  <p class="text-muted">The GPA calculations are based on the NEB (National Examinations Board) grading system as publicly documented. The results are estimates and may not exactly match official transcripts. Always refer to your official school or NEB-issued mark sheets for authoritative results.</p>
  <h4 class="fw-bold mt-4"><i class="bi bi-receipt text-primary me-2"></i>Bill Generator Disclaimer</h4>
  <p class="text-muted">The invoices and bills generated by our Bill Generator tool are for general business use and templates only. They should not be considered as legally binding financial documents without proper review. VAT calculations (13%) are based on current Nepali tax rates and may change. Consult a certified accountant for official tax filing.</p>
  <h4 class="fw-bold mt-4"><i class="bi bi-person-badge text-primary me-2"></i>Resume Generator Disclaimer</h4>
  <p class="text-muted">Resumes generated by our tool are templates to assist job seekers. We are not responsible for outcomes of job applications. We recommend proofreading and customizing your resume before submission.</p>
  <h4 class="fw-bold mt-4"><i class="bi bi-link-45deg text-primary me-2"></i>External Links</h4>
  <p class="text-muted">Our website may contain links to external websites. We have no control over the nature, content, and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorsement of the views expressed within them.</p>
  <h4 class="fw-bold mt-4"><i class="bi bi-envelope text-primary me-2"></i>Contact</h4>
  <p class="text-muted">If you have questions about this Disclaimer, please <a href="<?php echo $rootPath; ?>contact">contact us</a>.</p>
</div></div></div></div></section>
<?php include 'includes/footer.php'; ?>
